name: Validation

on:
  push:
    branches:
    - master

jobs:
  validation-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup repository
      run: |
        pip install conan
        conan remote add conan-iceshard https://conan.iceshard.net/
        conan remote add conan-bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    - name: Build
      run: |
        echo "Build your project here."
        ice
    - name: Verify
      run: |
        echo "Verify your project here."
